export const countries = [
  'India',
  'United States',
  'Canada',
  'United Kingdom',
  'Australia',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Japan',
  'China',
  'Brazil',
  'Mexico',
  'South Africa',
  'Singapore',
  'United Arab Emirates',
  'Saudi Arabia',
  'Netherlands',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'New Zealand',
  'Ireland',
  // add more later if needed
];

export const currencies = [
  'INR - Indian Rupee',
  'USD - US Dollar',
  'EUR - Euro',
  'GBP - British Pound',
  'AUD - Australian Dollar',
  'CAD - Canadian Dollar',
  'JPY - Japanese Yen',
  'CNY - Chinese Yuan',
  'BRL - Brazilian Real',
  'ZAR - South African Rand',
  'SGD - Singapore Dollar',
  'AED - UAE Dirham',
  'SAR - Saudi Riyal',
  'CHF - Swiss Franc',
  'SEK - Swedish Krona',
  'NOK - Norwegian Krone',
  'DKK - Danish Krone',
  'NZD - New Zealand Dollar',
];
